"""Initial tables: prices, sentiment, signals, trades

Revision ID: e3aecd7416dd
Revises: 
Create Date: 2026-02-15 16:00:26.463898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3aecd7416dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_history_symbol', 'price_history', ['symbol'], unique=False)
    op.create_index('ix_price_history_symbol_timestamp', 'price_history', ['symbol', 'timestamp'], unique=False)
    op.create_index('ix_price_history_timestamp', 'price_history', ['timestamp'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sentiment_scores_symbol', 'sentiment_scores', ['symbol'], unique=False)
    op.create_index('ix_sentiment_scores_symbol_timestamp', 'sentiment_scores', ['symbol', 'timestamp'], unique=False)
    op.create_index('ix_sentiment_scores_timestamp', 'sentiment_scores', ['timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', 'HOLD', name='signalaction'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('price_at_signal', sa.Float(), nullable=False),
    sa.Column('reasons', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('technical_indicators', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_symbol', 'signals', ['symbol'], unique=False)
    op.create_index('ix_signals_timestamp', 'signals', ['timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='tradestatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_index('ix_signals_timestamp', table_name='signals')
    op.drop_index('ix_signals_symbol', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_sentiment_scores_timestamp', table_name='sentiment_scores')
    op.drop_index('ix_sentiment_scores_symbol_timestamp', table_name='sentiment_scores')
    op.drop_index('ix_sentiment_scores_symbol', table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index('ix_price_history_timestamp', table_name='price_history')
    op.drop_index('ix_price_history_symbol_timestamp', table_name='price_history')
    op.drop_index('ix_price_history_symbol', table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###
